transformer:
  vocab_size: 10001
  context_length: 256
  num_layers: 4
  d_model: 512
  num_heads: 16
  d_ff: 2016
  theta: 10000
  ff_type: relu2
  qk_norm: true
  zero_init_projection: true

dataset:
  train_path: data/owt_train_tokens.npy
  valid_path: data/owt_valid_tokens.npy
  batch_size: 512

trainer:
  max_grad_norm: 1.0
  max_tokens: 327680000
  validation_steps: 100
  validate_every_n_steps: 500
  checkpoint_every_n_steps: 500
  checkpoint_path: checkpoints/owt/relu2_qknorm_zeroinit
  run_name: owt-train-relu2_qknorm_zeroinit

scheduler:
  min_lr: 1e-5
  max_lr: 2.623e-3
  warmup_steps_pct: 0.05
  base_batch_size: 64

optimizer:
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.1